{
  "comments": [
    {
      "key": {
        "uuid": "d99a30c1_35a0e219",
        "filename": "generator/generator_lib.py",
        "patchSetId": 2
      },
      "lineNbr": 252,
      "author": {
        "id": 1000015
      },
      "writtenOn": "2019-09-18T21:00:08Z",
      "side": 1,
      "message": "nit: Could do these prints only once, instead of once per file - might be nicer if someone makes an error which moves a lot of files out of the allowed directories",
      "revId": "a93616f95f86f4468e95163d5d88382bdc7cd16d",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "cae3a185_fc2c9d4c",
        "filename": "generator/generator_lib.py",
        "patchSetId": 2
      },
      "lineNbr": 252,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2019-09-18T21:01:48Z",
      "side": 1,
      "message": "Yep this returns after the first failing file is found, see line below with \"return 1\".",
      "parentUuid": "d99a30c1_35a0e219",
      "revId": "a93616f95f86f4468e95163d5d88382bdc7cd16d",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd",
      "unresolved": true
    }
  ]
}